### ISSUE TITLE
XML generators should guard against problematic text strings

### ISSUE THREAD

**Issue by fweimer** [sonatype/plexus-utils#19]
`org.codehaus.plexus.util.xml.XmlWriterUtil#writeComment(XMLWriter, String, int, int, int)` does not check if the comment includes a `"-->"` sequence.  This means that text contained in the command string could be interpreted as XML, possibly leading to XML injection issues, depending on how this method is being called.

**Comment by fweimer** [comment]
@kellyrob99 Why are you closing this issue?

**Comment by khmarbaise** [comment]
Because those issue belong here: https://github.com/codehaus-plexus/plexus-utils

**Comment by kellyrob99** [comment]
@fweimer Sorry, but we no longer own the development of this library and won't be releasing it in the future.
