### ISSUE TITLE
getSystemEnvVars garbling exported bash functions 

### ISSUE THREAD

**Issue by noelmcloughlin** [sonatype/plexus-utils#21]
Hi,

Could you investigate if 'getSystemEnvVars()' method in MAVEN CommandLineUtils class is garbling exported bash functions ?

https://github.com/sonatype/plexus-utils/blob/master/src/main/java/org/codehaus/plexus/util/cli/CommandLineUtils.java#L240

Refer to discussion at: https://bugzilla.redhat.com/show_bug.cgi?id=1306804

thanks
Noel

**Comment by mcculls** [comment]
This is no longer the canonical repository, this project has been moved to https://github.com/codehaus-plexus/plexus-utils (as noted in https://github.com/sonatype/plexus-utils/blob/master/README.md)
